### ISSUE TITLE
"cut_trailing_sentence()" sometimes removes complete dialogues

### ISSUE THREAD

**Issue by marktaiwan** [thadunge2/AIDungeon#20]
I noticed that the game would on occasion produce results that would cut off just as a character is about to speak. I think I identified at least one condition that causes this.

---

Let's say for example the raw output of one run ends with:
```
[...]
You walk pass your neighbour mowing his lawn, he turns to you and says, "Hey how's it going?"
[incomplete sentence fragment]
```
When passed to [`cut_trailing_sentence`](https://github.com/thadunge2/AIDungeon/blob/91dd376ed77da0a8caccce211a38c8a996aaf4ec/story/utils.py#L127), the function removes everything after the question mark, including the double quote:
```
[...]
You walk pass your neighbour mowing his lawn, he turns to you and says, "Hey how's it going?
```
The text is then passed to [`cut_trailing_quotes`](https://github.com/thadunge2/AIDungeon/blob/91dd376ed77da0a8caccce211a38c8a996aaf4ec/story/utils.py#L85), which removes the rest:
```
[...]
You walk pass your neighbour mowing his lawn, he turns to you and says, 
```
This issue only affect dialogues that ends with `?` or `!` but not `.` because in one of the earlier steps of `result_replace`, there is this line:
https://github.com/thadunge2/AIDungeon/blob/91dd376ed77da0a8caccce211a38c8a996aaf4ec/generator/gpt2/gpt2_generator.py#L66
I don't understand why this line is here, because dialogues _should_ end with its punctuation inside the quotes. \*shrug\*

I don't know the best way going about fixing this, my present solution is to move `cut_trailing_quotes` near the top of the function for it to remove actual incomplete quotes first, then change
```python
last_punc = max(text.rfind("."), text.rfind("!"), text.rfind("?"))
```
to include `"` as a valid character to end a sentence in.

---

One problem I can see with this is if the last sentence of the dialogue contains the string `you ask` or `you say`, it will get removed by `cut_trailing_action`, potentially resulting in a incomplete quote if the dialogue is 2 or more sentences long.

**Comment by thadunge2** [comment]
Yes, I've noticed it myself. This is why Nick coded it to put periods on the outside of quotes - "like this". However, it doesn't do that for question marks or exclamation points -- hence the problem. I've been looking into issues like this for a few days. This is pretty much the last remaining one of them.

**Comment by marktaiwan** [comment]
> This is why Nick coded it to put periods on the outside

Well sounds like a friggin stupid idea. I don't know anything about machine learning, but since the model is trained on a corpus of largely grammatically correct text, and the processed result is fed back to the model, I can't imagine doing this won't throw off the subsequent outputs in some way.

On a related note, right now the code truncates everything to the right of `>` to remove the output that emulates player actions. What do you think about we just remove the individual line instead by adding
```python
result = re.sub(r"(\n|^)>.*(?=\n|$)", r"\1", result)
```
to `result_replace`? ([sample](https://www.debuggex.com/r/XkAF90GVAb4bijXf))

I've been playing the game on my personal branch with the mentioned changes and it seems to be working well so far. If nothing else, I don't get any timeouts anymore.

**Comment by ShnitzelKiller** [comment]
Pull request #21 seeks to address this problem. It provides the option to use this behavior, where only the line is removed, and everything after it is kept. The exception is in dialogue, in which case the line is kept entirely (but the > is removed). Prompts with dialogue tend to be important for the flow, whereas those without tend to get repeated in the ensuing description, so these choices seem to give the best results.

**Comment by KennethSamael** [comment]
Let me see if I understand how this works. First it tries to find the end of the sentence, using punctuation as a guide. Let's pretend these examples are the last paragraphs of a longer text.

> You do something. You then say "I wanna try stopping in the middle of my quote. That would be funny

becomes

> You do something. You then say "I wanna try stopping in the middle of my quote.

Then it cuts off after the last quotation mark if it detects an uneven number of quotation marks.

> You do something. You then say

Then it cuts off the last part if it contains either `you say` or `you ask`. In this case, it doesn't use that exact phrasing, so it gets left like that.
However, if you start out with

> He says: "Stop bothering me. You ask too many questions".

then it detects `you ask` and cuts it off, even though it's not really a trailing action.

> He says: "Stop bothering me.

And since `cut_trailing_quotes` runs before `cut_trailing_action`, it gets left like that. Basically, the part that's supposed to handle the consequences of removing trailing quotes can end up creating another trailing quote. And `you say` and `you ask ` has tons of false positives. It would also cut off sentences like `"whatever you say, man"` or `he offers to grant any request you ask of him`.

I wanna scrap most of it and do something like this
```
    if text.count('"') % 2 is 0:
        before_last_punc = re.search("(\w|\W)*(\.|!|\?)(\")*", text)
    else:
        before_last_quot = re.search("(\w|\W)*(?=\")", text)
        if before_last_quot is not None:
            before_last_punc = re.search("(\w|\W)*(\.|!|\?)(\")*", before_last_quot.group(0))
        else:
            before_last_punc = None
    if before_last_punc is not None:
        last_punc = len(before_last_punc.group(0)) - 1
    else:
        last_punc = 0
```
Maybe there's a more elegant way, but this should find the last punctuation (or quotation mark if one immediately follows punctuation) when there's an even number of quotation marks, and if not, it finds the last punctuation that's before the last quotation mark. That should by itself cut off trailing quotes and actions. Only problem is that it then tries to cut off `<` and `>`, potentially leaving us with another fragmented sentence. Is there any reason we can't just cut them out of the text at the start of the function, before trying to cut off any trailing sentence?
```
    text = re.sub("[<>][\w\W]*", "", text)
```

Maybe they know something I don't and there's a really good reason to do things their way, but it seems to me like this produces a more consistent and clean output.

**Comment by ShnitzelKiller** [comment]
My PR #23 addresses this problem simply by finding the last sentence-end punctuation, then putting a quote at the end if necessary. I feel that this elegantly handles the above issues:

> 1. You do something. You then say "I wanna try stopping in the middle of my quote. That would be funny
> 2. You do something. You then say "I wanna try stopping in the middle of my quote.
> 3. You do something. You then say "I wanna try stopping in the middle of my quote."

> 1. You open your mouth. You then proceed to say "I have no sentence and I must scream
> 2. You open your mouth.

It also handles the punctuation order without needing special cases:

> 1. You do something. You then say "I like to speak with correct grammar."
> 2. You do something. You then say "I like to speak with correct grammar.
> 3. You do something. You then say "I like to speak with correct grammar."

As for
> He says: "Stop bothering me. You ask too many questions".

We would need to add a clause specifying that "you ask", "you say", etc. are not detected inside of quotation marks, which isn't too difficult but is not currently done.
Note that with my PR #21, disabling output trimming also fixes this problem, because cut_trailing_actions() is not called, and my version of filtering out actions explicitly looks for action prompts, on a new line, so the above would not get cut off.

**Comment by thadunge2** [comment]
> On a related note, right now the code truncates everything to the right of `>` to remove the output that emulates player actions. What do you think about we just remove the individual line instead by adding
> 
> ```python
> result = re.sub(r"(\n|^)>.*(?=\n|$)", r"\1", result)
> ```
> 
> to `result_replace`? ([sample](https://www.debuggex.com/r/XkAF90GVAb4bijXf))

I'm skeptical, because it's a response to a prompt that the player didn't enter and was cut. There's a reason the Mormon just trashed everything that didn't really fit the prompt.

But if you want to discuss it further, open a new issue. Closing this one as #23 was merged.
